version: '3.0'

services: 
  noormeister-backend:
    build: 
      context: ./backend
    expose: 
      3003
    ports: 3003:3003
    volumes: 
      - .:/server
      - /server/node_modules
    command: npm run dev
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_HOST: mysql
      MYSLQL_DATABASE: noo
      MYSQL_ROOT_PASSWORD: qwerty
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:

      
    